using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Ow.Utils;

namespace Ow.Net.netty.commands
{
    class GroupPlayerShipModule : command_i3O
    {
        public static short ID = 27619;

        public const short vari3Q = 173;
        public const short varv3L = 61;
        public const short varB1i = 169;
        public const short vartX = 69;
        public const short SPECTRUM = 33;
        public const short var6m = 64;
        public const short varM3T = 149;
        public const short varTr = 119;
        public const short varWj = 141;
        public const short varx3n = 51;
        public const short vara1B = 54;
        public const short varB2B = 82;
        public const short varg3 = 48;
        public const short GOLD = 194;
        public const short varW4Q = 22;
        public const short LIBERATOR = 6;
        public const short vark2D = 100;
        public const short varC1R = 180;
        public const short var343 = 50;
        public const short varE14 = 53;
        public const short varoj = 138;
        public const short varz2h = 95;
        public const short varV37 = 132;
        public const short varu3K = 43;
        public const short varX23 = 120;
        public const short vart3h = 9;
        public const short PET = 162;
        public const short varg1B = 37;
        public const short varA7 = 190;
        public const short var5b = 175;
        public const short DEFAULT = 1;
        public const short varW3h = 147;
        public const short UFONIT = 72;
        public const short varI0 = 38;
        public const short varX4v = 98;
        public const short varMc = 97;
        public const short varb1s = 96;
        public const short SENTINEL = 34;
        public const short varGp = 39;
        public const short varV1Q = 107;
        public const short varA4D = 160;
        public const short varQ2O = 104;   
        public const short ADEPT = 12;
        public const short varY4v = 87;
        public const short vary2g = 113;
        public const short varf3F = 40;
        public const short varf40 = 60;
        public const short varn2I = 178;
        public const short varu37 = 81;
        public const short varA4Z = 108;
        public const short UFO = 73;
        public const short varG1Q = 57;
        public const short vara36 = 111;
        public const short varp3h = 145;
        public const short varUr = 115;
        public const short vare3M = 159;
        public const short varm2f = 118;
        public const short EXALTED = 30;
        public const short varC1 = 85;
        public const short WRECK = 165;
        public const short varc1u = 7;
        public const short varL4q = 92;
        public const short varA3w = 117;
        public const short LIGHTNING = 14;
        public const short varv1S = 126;
        public const short varL23 = 140;
        public const short SOLACE = 31;
        public const short varqp = 143;
        public const short varg4J = 21;
        public const short AVENGER = 28;
        public const short varx3e = 183;
        public const short varJ1 = 109;
        public const short StreuneR = 58;
        public const short varL1v = 103;
        public const short varI4k = 193;
        public const short varr1t = 197;
        public const short varC2I = 67;
        public const short vari38 = 52;
        public const short var348 = 114;
        public const short varg1q = 181;
        public const short varN4G = 144;
        public const short varBe = 17; 
        public const short varQ2M = 137;
        public const short CENTAUR = 47;   
        public const short varG3L = 176;
        public const short varC13 = 68;
        public const short var84g = 121;
        public const short varn1e = 74;
        public const short SATURN = 46;
        public const short varPe = 66;
        public const short varE4h = 44;
        public const short varTb = 188;
        public const short varn3s = 71;
        public const short varo8 = 55;
        public const short vark3P = 84;
        public const short varF2c = 177;
        public const short varK5 = 63;
        public const short var34M = 133;
        public const short VETERAN = 29;
        public const short varXm = 135;
        public const short varZ31 = 106;
        public const short varF2v = 110;
        public const short NONE = 0;
        public const short varN1B = 79;
        public const short varF1s = 91;
        public const short varYj = 11;
        public const short varH1P = 76;
        public const short var74z = 186;
        public const short var42m = 146;
        public const short varge = 187;
        public const short varz2Z = 101;
        public const short varM2h = 23;
        public const short varQd = 80;
        public const short varT1N = 130;
        public const short varU1Y = 179;
        public const short vara2M = 171;
        public const short varu3v = 161;
        public const short BRONZE = 196;
        public const short varU2p = 105;
        public const short varb4H = 45;
        public const short AEGIS = 18;
        public const short varO4D = 156;
        public const short varfX = 136;
        public const short varr18 = 86;
        public const short vark3w = 128;
        public const short varx3C = 157;
        public const short varN4T = 163;
        public const short var84X = 192;
        public const short varJe = 139;
        public const short varQ27 = 2;
        public const short varx1r = 90;
        public const short varU2S = 166;
        public const short varU4d = 127;
        public const short varU1r = 189;
        public const short varm3e = 112;
        public const short varD3K = 164;
        public const short varM6 = 62;
        public const short varU33 = 93;
        public const short varS2j = 167;
        public const short vard1x = 77;
        public const short varp2P = 172;
        public const short var84a = 125;
        public const short vars3R = 134;
        public const short var01r = 83;
        public const short varpL = 151;
        public const short varX7 = 170;
        public const short varS3A = 59;
        public const short varYP = 155;
        public const short var32C = 99;
        public const short varQ2l = 191;
        public const short REVENGE = 26;
        public const short varm27 = 65;
        public const short varB1O = 78;
        public const short varUn = 150;
        public const short var9N = 20;
        public const short varo2b = 116;
        public const short var03U = 124;
        public const short vari3k = 8;
        public const short varoE = 129;
        public const short varb1g = 88;
        public const short varCQ = 102;
        public const short vara1R = 182;
        public const short CORSAIR = 13;
        public const short varC1V = 94;
        public const short varY1q = 89;
        public const short var64r = 184;
        public const short varE17 = 122;
        public const short BASTION = 27;
        public const short varP3R = 49;
        public const short varV3H = 16;
        public const short SILVER = 195;
        public const short varo1w = 152;
        public const short vars1f = 154;
        public const short varZ1 = 153;
        public const short varG2Y = 4;
        public const short varG2g = 25;
        public const short varw3Y = 15;
        public const short varP1p = 5;
        public const short DIMINISHER = 32;
        public const short var71r = 19;
        public const short varL2u = 148;
        public const short SPEARHEAD = 42;
        public const short varr3y = 158;
        public const short var64S = 3;
        public const short varS2v = 75;
        public const short varW1k = 142;
        public const short varof = 70;
        public const short varP4L = 185;
        public const short varJ4K = 56;
        public const short varSO = 123;
        public const short VENOM = 35;
        public const short varA4C = 36;
        public const short varX3N = 10;
        public const short CITADEL = 41;
        public const short ENFORCER = 24;
        public const short varb4G = 131;
        public const short varj28 = 174;
        public const short var91l = 168;

        public short shipId = 0;

        public GroupPlayerShipModule(short shipId)
        {
            this.shipId = shipId;
        }

        public override byte[] write()
        {
            var param1 = new ByteArray(ID);
            super(param1);
            param1.writeShort(this.shipId);
            return param1.Message.ToArray();
        }
    }
}
