package simulator.system.ships;

/**
 Created by bpdev on 31/01/2015.
 Edited by LEJYONER.
 */
public class ShipsConstants {

    public static int STREUNER_ID;
    public static int STREUNER_BOSS;
    public static int STREUNER_UBER_ID;
    public static int LORDAKIA_ID;
    public static int LORDAKIA_BOSS_ID;
    public static int LORDAKIA_UBER_ID;
    public static int SAIMON_ID;
    public static int SAIMON_BOSS_ID;
    public static int SAIMON_UBER_ID;
    public static int MORDON_ID;
    public static int MORDON_BOSS_ID;
    public static int MORDON_UBER_ID;
    public static int DEVOLARIUM_ID;
    public static int DEVOLARIUM_BOSS_ID;
    public static int DEVOLARIUM_UBER_ID;
    public static int SIBELON_ID;
    public static int SIBELON_BOSS_ID;
    public static int SIBELON_UBER_ID;
    public static int SIBELONIT_ID;
    public static int SIBELONIT_BOSS_ID;
    public static int SIBELONIT_UBER_ID;
    public static int LORDAKIUM_ID;
    public static int LORDAKIUM_BOSS_ID;
    public static int LORDAKIUM_UBER_ID;
    public static int KRISTALLIN_ID;
    public static int KRISTALLIN_BOSS_ID;
    public static int KRISTALLIN_UBER_ID;
    public static int KRISTALLON_ID;
    public static int KRISTALLON_BOSS_ID;
    public static int KRISTALLON_UBER_ID;
    public static int STREUNER_2_ID;
    public static int STREUNER_2_BOSS_ID;
    public static int STREUNER_2_UBER_ID;
    public static int CUBIKON_ID  = 80;
    public static int PROTEGIT_ID = 81;
    public static int INTERCEPTOR_ID;
    public static int ANNIHILATOR_ID;
    public static int BARRACUDA_ID;
    public static int SABOTEUR_ID;
    public static int BATTLERAY_ID;
    public static int VAGRANT_ID;
    public static int MARUADER_ID;
    public static int CORSAIR_ID;
    public static int RAVAGER_ID;
    public static int OUTCAST_ID;
    public static int HOOLIGAN_ID;
    public static int CONVICT_ID;
    public static int CENTURY_FALCON_ID;
    public static int KUCURBIUM_ID;
    public static int KUCURBIUM_BOSS_ID;
    public static int INFERNAL_ID;
    public static int MELTER_ID;
    public static int SCORCHER_ID;
    public static int DEVOURER_ID;
    public static int SANEJIEWZ_ID;
    public static int ICY_ID = 103;
    public static int ICY_METEOROID_ID = 101;
    public static int BINARY_BOT_ID;
    public static int SUNBURST_LORDAKIUM_ID;
    public static int CURKUBITOR_ID;
    public static int CURKUBITOR_BOSS_ID;
    public static int SIBELON_EMPEROR_ID;
    public static int LORDAKIUM_EMPEROR_ID;
    public static int KRISTALLON_EMPEROR_ID;
    public static int SPACEBALL_SUMMER    = 442;
    public static int SPACEBALL_WINTER    = 443;
    public static int SPACEBALL_SOCCER    = 444;
    public static final int GOLIATH_BASTION        = 59;
    public static final int GOLIATH_ENFORCER       = 56;
    public static final int GOLIATH_CENTAUR        = 110;
    public static final int GOLIATH_DIMINISHER     = 64;
    public static final int GOLIATH_EXALTED        = 62;
    public static final int GOLIATH_GOAL           = 88;
    public static final int GOLIATH_KICK           = 86;
    public static final int GOLIATH_PEACEMAKER     = 142;
    public static final int GOLIATH_REFEREE        = 87;
    public static final int GOLIATH_SATURN         = 109;
    public static final int GOLIATH_SENTINEL       = 66;
    public static final int GOLIATH_SOLACE         = 63;
    public static final int GOLIATH_SOVEREIGN      = 141;
    public static final int GOLIATH_SPECTRUM       = 65;
    public static final int GOLIATH_VANQUISHER     = 140;
    public static final int GOLIATH_VENOM          = 67;
    public static final int GOLIATH_VETERAN        = 61;
    public static final int GOLIATH_HEZARFEN       = 155;
    public static final int GOLIATH_INDEPENDENCE   = 57;
    public static final int CYBORG                 = 445;
    public static final int HAMMERCLAW             = 446;
    public static final int GOLIATH_SPECTRUM_FROST = 447;
    public static final int GOLIATH_SENTINEL_FROST = 448;
    public static final int GOLIATH_SENTINEL_LEGEND = 449;
    public static final int GOLIATH_SPECTRUM_LEGEND = 450;
    public static final int G_CHAMPION_LEGEND = 451;
    public static final int CYBORG_LAVA = 452;
    public static final int HAMMERCLAW_LAVA = 453;
    public static final int SURGEON = 454;
    public static final int SURGEON_CICADA = 455;
    public static final int SURGEON_LOCUST = 456;
	public static final int GOLIATH = 10;
	public static final int GOLIATH_RAZER = 153;
}
